{% set name = "py-mathjax" %}
{% set version = "3.0.0" %}
# {% set dep_ver = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 01312f06eea1f21909b606232a49dc6482e9185be0614bbb7765e37723695556
  patches:
    - conda.patch

build:
  noarch: python
  number: 0
  entry_points:
    - py-mathjax-path = pymathjax.__main__:cli
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - mathjax ={{ version }}

test:
  imports:
    - pymathjax
  commands:
    - py-mathjax-path
    - py-mathjax-path --url
    - py-mathjax-path --help

about:
  home: https://github.com/kiwi0fruit/py-mathjax
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: "Installs mathjax conda package in pip and conda."
  doc_url: https://github.com/kiwi0fruit/py-mathjax
  dev_url: https://github.com/kiwi0fruit/py-mathjax

extra:
  recipe-maintainers:
    - kiwi0fruit
