#!/bin/bash
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
mathjax="$(dirname "${script_dir}")/lib/mathjax/es5/"
if [[ -d "$mathjax" ]]; then
    echo "$mathjax"
else
    echo -e "Error: $mathjax dir was not found"
    exit 1
fi
