#!/bin/bash
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
mathjax="$(dirname "${script_dir}")/lib/mathjax/MathJax.js"
if [[ -f "$mathjax" ]]; then
    echo "$mathjax"
else
    echo -e "Error: $mathjax file was not found"
    exit 1
fi
