{% set name = "mathjax" %}
{% set version = "2.7.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mathjax/MathJax/archive/{{ version }}.tar.gz
  sha256: 71ea2429b1b5b5d796d3f89303a33d61ce8459897b48973d768261e33d6268c0

build:
   number: 0

test:
  commands:
    - mathjax-path

about:
  home: https://github.com/mathjax/MathJax
  license: "Apache 2.0"
  license_family: Apache
  license_file: LICENSE
  summary: "Beautiful math in all browsers. MathJax is an open-source JavaScript display engine for LaTeX, MathML, and AsciiMath notation that works in all browsers. (use mathjax-path script)"
  doc_url: https://github.com/mathjax/MathJax
  dev_url: https://github.com/mathjax/MathJax

extra:
  recipe-maintainers:
    - kiwi0fruit
